id: PC91C4D33
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA25094
  instance_id: http://purl.bdrc.io/resource/IE25094
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - བསེ་བསྡུས་གྲྭ།
  alt_title:
    en-x-mixed:
    - Tshad maʼi dgoṅs don rtsa grelo mkhas paʼi mgul rgyan /Sudhiprasaka daṅ bse
      Nag-dbaṅ-bkra-ʹsis kyis brtsams.
    zh-hans:
    - 因明学概要及其注释
  author: http://purl.bdrc.io/resource/P254
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    2c87c6a048a24d8c8a38458512f52ac5:
      title: པོད ༡་བསེ་བསྡུས་གྲྭ།
      volume_number: 1
      base_file: UT25094_4813_0000.txt
      reference: http://purl.bdrc.io/resource/VL669C0BEE0850C645
      image_group: '4813'
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W25094
  - http://purl.bdrc.io/resource/MW25094
  ocr_software: Namsel
created_at: '2021-12-22T11:10:16.288934'
last_modified_at: '2021-12-22T11:10:16.288941'
